version: 2
updates:
  - package-ecosystem: gomod
    directories: ["/", "/operator"]
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: docker
    directories: ["/deploy/compose", "/operator"]
    schedule:
      interval: weekly
    groups:
      docker:
        patterns: ["*"]
